dist: xenial
language: python
group: edge
python: 3.6

matrix:
  include:
    - os: windows
      language: generic
      env: TESTENV=py37-pyqt511
  fast_finish: true
  allow_failures:
    # https://github.com/qutebrowser/qutebrowser/issues/4055
    - os: linux
      env: TESTENV=py36-pyqt510

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/qutebrowser/qutebrowser/.cache

install:
  - bash scripts/dev/ci/travis_install.sh
  - ulimit -c unlimited

script:
  - bash scripts/dev/ci/travis_run.sh

after_success:
  - '[[ $TESTENV == *-cov ]] && codecov -e TESTENV -X gcov'

after_failure:
  - bash scripts/dev/ci/travis_backtrace.sh

notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
  irc:
    channels:
      - "chat.freenode.net#qutebrowser-dev"
    on_success: always
    on_failure: always
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "%{compare_url} - %{build_url}"
